/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tglog_v3.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "tglog_v3.pb-c.h"
void   tglog_v3__log__init
                     (TglogV3__Log         *message)
{
  static const TglogV3__Log init_value = TGLOG_V3__LOG__INIT;
  *message = init_value;
}
size_t tglog_v3__log__get_packed_size
                     (const TglogV3__Log *message)
{
  assert(message->base.descriptor == &tglog_v3__log__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tglog_v3__log__pack
                     (const TglogV3__Log *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tglog_v3__log__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tglog_v3__log__pack_to_buffer
                     (const TglogV3__Log *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tglog_v3__log__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TglogV3__Log *
       tglog_v3__log__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TglogV3__Log *)
     protobuf_c_message_unpack (&tglog_v3__log__descriptor,
                                allocator, len, data);
}
void   tglog_v3__log__free_unpacked
                     (TglogV3__Log *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tglog_v3__log__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tglog_v3__auth_req__labels_entry__init
                     (TglogV3__AuthReq__LabelsEntry         *message)
{
  static const TglogV3__AuthReq__LabelsEntry init_value = TGLOG_V3__AUTH_REQ__LABELS_ENTRY__INIT;
  *message = init_value;
}
void   tglog_v3__auth_req__annotations_entry__init
                     (TglogV3__AuthReq__AnnotationsEntry         *message)
{
  static const TglogV3__AuthReq__AnnotationsEntry init_value = TGLOG_V3__AUTH_REQ__ANNOTATIONS_ENTRY__INIT;
  *message = init_value;
}
void   tglog_v3__auth_req__init
                     (TglogV3__AuthReq         *message)
{
  static const TglogV3__AuthReq init_value = TGLOG_V3__AUTH_REQ__INIT;
  *message = init_value;
}
size_t tglog_v3__auth_req__get_packed_size
                     (const TglogV3__AuthReq *message)
{
  assert(message->base.descriptor == &tglog_v3__auth_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tglog_v3__auth_req__pack
                     (const TglogV3__AuthReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tglog_v3__auth_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tglog_v3__auth_req__pack_to_buffer
                     (const TglogV3__AuthReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tglog_v3__auth_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TglogV3__AuthReq *
       tglog_v3__auth_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TglogV3__AuthReq *)
     protobuf_c_message_unpack (&tglog_v3__auth_req__descriptor,
                                allocator, len, data);
}
void   tglog_v3__auth_req__free_unpacked
                     (TglogV3__AuthReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tglog_v3__auth_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tglog_v3__auth_rsp__init
                     (TglogV3__AuthRsp         *message)
{
  static const TglogV3__AuthRsp init_value = TGLOG_V3__AUTH_RSP__INIT;
  *message = init_value;
}
size_t tglog_v3__auth_rsp__get_packed_size
                     (const TglogV3__AuthRsp *message)
{
  assert(message->base.descriptor == &tglog_v3__auth_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tglog_v3__auth_rsp__pack
                     (const TglogV3__AuthRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tglog_v3__auth_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tglog_v3__auth_rsp__pack_to_buffer
                     (const TglogV3__AuthRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tglog_v3__auth_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TglogV3__AuthRsp *
       tglog_v3__auth_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TglogV3__AuthRsp *)
     protobuf_c_message_unpack (&tglog_v3__auth_rsp__descriptor,
                                allocator, len, data);
}
void   tglog_v3__auth_rsp__free_unpacked
                     (TglogV3__AuthRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tglog_v3__auth_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tglog_v3__log_req__labels_entry__init
                     (TglogV3__LogReq__LabelsEntry         *message)
{
  static const TglogV3__LogReq__LabelsEntry init_value = TGLOG_V3__LOG_REQ__LABELS_ENTRY__INIT;
  *message = init_value;
}
void   tglog_v3__log_req__annotations_entry__init
                     (TglogV3__LogReq__AnnotationsEntry         *message)
{
  static const TglogV3__LogReq__AnnotationsEntry init_value = TGLOG_V3__LOG_REQ__ANNOTATIONS_ENTRY__INIT;
  *message = init_value;
}
void   tglog_v3__log_req__init
                     (TglogV3__LogReq         *message)
{
  static const TglogV3__LogReq init_value = TGLOG_V3__LOG_REQ__INIT;
  *message = init_value;
}
size_t tglog_v3__log_req__get_packed_size
                     (const TglogV3__LogReq *message)
{
  assert(message->base.descriptor == &tglog_v3__log_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tglog_v3__log_req__pack
                     (const TglogV3__LogReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tglog_v3__log_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tglog_v3__log_req__pack_to_buffer
                     (const TglogV3__LogReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tglog_v3__log_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TglogV3__LogReq *
       tglog_v3__log_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TglogV3__LogReq *)
     protobuf_c_message_unpack (&tglog_v3__log_req__descriptor,
                                allocator, len, data);
}
void   tglog_v3__log_req__free_unpacked
                     (TglogV3__LogReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tglog_v3__log_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tglog_v3__log_rsp__init
                     (TglogV3__LogRsp         *message)
{
  static const TglogV3__LogRsp init_value = TGLOG_V3__LOG_RSP__INIT;
  *message = init_value;
}
size_t tglog_v3__log_rsp__get_packed_size
                     (const TglogV3__LogRsp *message)
{
  assert(message->base.descriptor == &tglog_v3__log_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tglog_v3__log_rsp__pack
                     (const TglogV3__LogRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tglog_v3__log_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tglog_v3__log_rsp__pack_to_buffer
                     (const TglogV3__LogRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tglog_v3__log_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TglogV3__LogRsp *
       tglog_v3__log_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TglogV3__LogRsp *)
     protobuf_c_message_unpack (&tglog_v3__log_rsp__descriptor,
                                allocator, len, data);
}
void   tglog_v3__log_rsp__free_unpacked
                     (TglogV3__LogRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tglog_v3__log_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tglog_v3__heartbeat_req__init
                     (TglogV3__HeartbeatReq         *message)
{
  static const TglogV3__HeartbeatReq init_value = TGLOG_V3__HEARTBEAT_REQ__INIT;
  *message = init_value;
}
size_t tglog_v3__heartbeat_req__get_packed_size
                     (const TglogV3__HeartbeatReq *message)
{
  assert(message->base.descriptor == &tglog_v3__heartbeat_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tglog_v3__heartbeat_req__pack
                     (const TglogV3__HeartbeatReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tglog_v3__heartbeat_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tglog_v3__heartbeat_req__pack_to_buffer
                     (const TglogV3__HeartbeatReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tglog_v3__heartbeat_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TglogV3__HeartbeatReq *
       tglog_v3__heartbeat_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TglogV3__HeartbeatReq *)
     protobuf_c_message_unpack (&tglog_v3__heartbeat_req__descriptor,
                                allocator, len, data);
}
void   tglog_v3__heartbeat_req__free_unpacked
                     (TglogV3__HeartbeatReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tglog_v3__heartbeat_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tglog_v3__heartbeat_rsp__init
                     (TglogV3__HeartbeatRsp         *message)
{
  static const TglogV3__HeartbeatRsp init_value = TGLOG_V3__HEARTBEAT_RSP__INIT;
  *message = init_value;
}
size_t tglog_v3__heartbeat_rsp__get_packed_size
                     (const TglogV3__HeartbeatRsp *message)
{
  assert(message->base.descriptor == &tglog_v3__heartbeat_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tglog_v3__heartbeat_rsp__pack
                     (const TglogV3__HeartbeatRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tglog_v3__heartbeat_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tglog_v3__heartbeat_rsp__pack_to_buffer
                     (const TglogV3__HeartbeatRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tglog_v3__heartbeat_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TglogV3__HeartbeatRsp *
       tglog_v3__heartbeat_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TglogV3__HeartbeatRsp *)
     protobuf_c_message_unpack (&tglog_v3__heartbeat_rsp__descriptor,
                                allocator, len, data);
}
void   tglog_v3__heartbeat_rsp__free_unpacked
                     (TglogV3__HeartbeatRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tglog_v3__heartbeat_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tglog_v3__req_header__init
                     (TglogV3__ReqHeader         *message)
{
  static const TglogV3__ReqHeader init_value = TGLOG_V3__REQ_HEADER__INIT;
  *message = init_value;
}
size_t tglog_v3__req_header__get_packed_size
                     (const TglogV3__ReqHeader *message)
{
  assert(message->base.descriptor == &tglog_v3__req_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tglog_v3__req_header__pack
                     (const TglogV3__ReqHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tglog_v3__req_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tglog_v3__req_header__pack_to_buffer
                     (const TglogV3__ReqHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tglog_v3__req_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TglogV3__ReqHeader *
       tglog_v3__req_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TglogV3__ReqHeader *)
     protobuf_c_message_unpack (&tglog_v3__req_header__descriptor,
                                allocator, len, data);
}
void   tglog_v3__req_header__free_unpacked
                     (TglogV3__ReqHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tglog_v3__req_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tglog_v3__req__init
                     (TglogV3__Req         *message)
{
  static const TglogV3__Req init_value = TGLOG_V3__REQ__INIT;
  *message = init_value;
}
size_t tglog_v3__req__get_packed_size
                     (const TglogV3__Req *message)
{
  assert(message->base.descriptor == &tglog_v3__req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tglog_v3__req__pack
                     (const TglogV3__Req *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tglog_v3__req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tglog_v3__req__pack_to_buffer
                     (const TglogV3__Req *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tglog_v3__req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TglogV3__Req *
       tglog_v3__req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TglogV3__Req *)
     protobuf_c_message_unpack (&tglog_v3__req__descriptor,
                                allocator, len, data);
}
void   tglog_v3__req__free_unpacked
                     (TglogV3__Req *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tglog_v3__req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tglog_v3__rsp_header__init
                     (TglogV3__RspHeader         *message)
{
  static const TglogV3__RspHeader init_value = TGLOG_V3__RSP_HEADER__INIT;
  *message = init_value;
}
size_t tglog_v3__rsp_header__get_packed_size
                     (const TglogV3__RspHeader *message)
{
  assert(message->base.descriptor == &tglog_v3__rsp_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tglog_v3__rsp_header__pack
                     (const TglogV3__RspHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tglog_v3__rsp_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tglog_v3__rsp_header__pack_to_buffer
                     (const TglogV3__RspHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tglog_v3__rsp_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TglogV3__RspHeader *
       tglog_v3__rsp_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TglogV3__RspHeader *)
     protobuf_c_message_unpack (&tglog_v3__rsp_header__descriptor,
                                allocator, len, data);
}
void   tglog_v3__rsp_header__free_unpacked
                     (TglogV3__RspHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tglog_v3__rsp_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tglog_v3__rsp__init
                     (TglogV3__Rsp         *message)
{
  static const TglogV3__Rsp init_value = TGLOG_V3__RSP__INIT;
  *message = init_value;
}
size_t tglog_v3__rsp__get_packed_size
                     (const TglogV3__Rsp *message)
{
  assert(message->base.descriptor == &tglog_v3__rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tglog_v3__rsp__pack
                     (const TglogV3__Rsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tglog_v3__rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tglog_v3__rsp__pack_to_buffer
                     (const TglogV3__Rsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tglog_v3__rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TglogV3__Rsp *
       tglog_v3__rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TglogV3__Rsp *)
     protobuf_c_message_unpack (&tglog_v3__rsp__descriptor,
                                allocator, len, data);
}
void   tglog_v3__rsp__free_unpacked
                     (TglogV3__Rsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tglog_v3__rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor tglog_v3__log__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__Log, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__Log, content),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(TglogV3__Log, seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tglog_v3__log__field_indices_by_name[] = {
  1,   /* field[1] = content */
  0,   /* field[0] = name */
  2,   /* field[2] = seq */
};
static const ProtobufCIntRange tglog_v3__log__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor tglog_v3__log__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tglog_v3.Log",
  "Log",
  "TglogV3__Log",
  "tglog_v3",
  sizeof(TglogV3__Log),
  3,
  tglog_v3__log__field_descriptors,
  tglog_v3__log__field_indices_by_name,
  1,  tglog_v3__log__number_ranges,
  (ProtobufCMessageInit) tglog_v3__log__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tglog_v3__auth_req__labels_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__AuthReq__LabelsEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__AuthReq__LabelsEntry, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tglog_v3__auth_req__labels_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange tglog_v3__auth_req__labels_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tglog_v3__auth_req__labels_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tglog_v3.AuthReq.LabelsEntry",
  "LabelsEntry",
  "TglogV3__AuthReq__LabelsEntry",
  "tglog_v3",
  sizeof(TglogV3__AuthReq__LabelsEntry),
  2,
  tglog_v3__auth_req__labels_entry__field_descriptors,
  tglog_v3__auth_req__labels_entry__field_indices_by_name,
  1,  tglog_v3__auth_req__labels_entry__number_ranges,
  (ProtobufCMessageInit) tglog_v3__auth_req__labels_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tglog_v3__auth_req__annotations_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__AuthReq__AnnotationsEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__AuthReq__AnnotationsEntry, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tglog_v3__auth_req__annotations_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange tglog_v3__auth_req__annotations_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tglog_v3__auth_req__annotations_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tglog_v3.AuthReq.AnnotationsEntry",
  "AnnotationsEntry",
  "TglogV3__AuthReq__AnnotationsEntry",
  "tglog_v3",
  sizeof(TglogV3__AuthReq__AnnotationsEntry),
  2,
  tglog_v3__auth_req__annotations_entry__field_descriptors,
  tglog_v3__auth_req__annotations_entry__field_indices_by_name,
  1,  tglog_v3__auth_req__annotations_entry__number_ranges,
  (ProtobufCMessageInit) tglog_v3__auth_req__annotations_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tglog_v3__auth_req__field_descriptors[2] =
{
  {
    "labels",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TglogV3__AuthReq, n_labels),
    offsetof(TglogV3__AuthReq, labels),
    &tglog_v3__auth_req__labels_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "annotations",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TglogV3__AuthReq, n_annotations),
    offsetof(TglogV3__AuthReq, annotations),
    &tglog_v3__auth_req__annotations_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tglog_v3__auth_req__field_indices_by_name[] = {
  1,   /* field[1] = annotations */
  0,   /* field[0] = labels */
};
static const ProtobufCIntRange tglog_v3__auth_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tglog_v3__auth_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tglog_v3.AuthReq",
  "AuthReq",
  "TglogV3__AuthReq",
  "tglog_v3",
  sizeof(TglogV3__AuthReq),
  2,
  tglog_v3__auth_req__field_descriptors,
  tglog_v3__auth_req__field_indices_by_name,
  1,  tglog_v3__auth_req__number_ranges,
  (ProtobufCMessageInit) tglog_v3__auth_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tglog_v3__auth_rsp__field_descriptors[1] =
{
  {
    "token",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__AuthRsp, token),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tglog_v3__auth_rsp__field_indices_by_name[] = {
  0,   /* field[0] = token */
};
static const ProtobufCIntRange tglog_v3__auth_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tglog_v3__auth_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tglog_v3.AuthRsp",
  "AuthRsp",
  "TglogV3__AuthRsp",
  "tglog_v3",
  sizeof(TglogV3__AuthRsp),
  1,
  tglog_v3__auth_rsp__field_descriptors,
  tglog_v3__auth_rsp__field_indices_by_name,
  1,  tglog_v3__auth_rsp__number_ranges,
  (ProtobufCMessageInit) tglog_v3__auth_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tglog_v3__log_req__labels_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__LogReq__LabelsEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__LogReq__LabelsEntry, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tglog_v3__log_req__labels_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange tglog_v3__log_req__labels_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tglog_v3__log_req__labels_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tglog_v3.LogReq.LabelsEntry",
  "LabelsEntry",
  "TglogV3__LogReq__LabelsEntry",
  "tglog_v3",
  sizeof(TglogV3__LogReq__LabelsEntry),
  2,
  tglog_v3__log_req__labels_entry__field_descriptors,
  tglog_v3__log_req__labels_entry__field_indices_by_name,
  1,  tglog_v3__log_req__labels_entry__number_ranges,
  (ProtobufCMessageInit) tglog_v3__log_req__labels_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tglog_v3__log_req__annotations_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__LogReq__AnnotationsEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__LogReq__AnnotationsEntry, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tglog_v3__log_req__annotations_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange tglog_v3__log_req__annotations_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tglog_v3__log_req__annotations_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tglog_v3.LogReq.AnnotationsEntry",
  "AnnotationsEntry",
  "TglogV3__LogReq__AnnotationsEntry",
  "tglog_v3",
  sizeof(TglogV3__LogReq__AnnotationsEntry),
  2,
  tglog_v3__log_req__annotations_entry__field_descriptors,
  tglog_v3__log_req__annotations_entry__field_indices_by_name,
  1,  tglog_v3__log_req__annotations_entry__number_ranges,
  (ProtobufCMessageInit) tglog_v3__log_req__annotations_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tglog_v3__log_req__field_descriptors[3] =
{
  {
    "labels",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TglogV3__LogReq, n_labels),
    offsetof(TglogV3__LogReq, labels),
    &tglog_v3__log_req__labels_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "annotations",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TglogV3__LogReq, n_annotations),
    offsetof(TglogV3__LogReq, annotations),
    &tglog_v3__log_req__annotations_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "logs",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TglogV3__LogReq, n_logs),
    offsetof(TglogV3__LogReq, logs),
    &tglog_v3__log__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tglog_v3__log_req__field_indices_by_name[] = {
  1,   /* field[1] = annotations */
  0,   /* field[0] = labels */
  2,   /* field[2] = logs */
};
static const ProtobufCIntRange tglog_v3__log_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor tglog_v3__log_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tglog_v3.LogReq",
  "LogReq",
  "TglogV3__LogReq",
  "tglog_v3",
  sizeof(TglogV3__LogReq),
  3,
  tglog_v3__log_req__field_descriptors,
  tglog_v3__log_req__field_indices_by_name,
  1,  tglog_v3__log_req__number_ranges,
  (ProtobufCMessageInit) tglog_v3__log_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tglog_v3__log_rsp__field_descriptors[1] =
{
  {
    "seqs",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(TglogV3__LogRsp, n_seqs),
    offsetof(TglogV3__LogRsp, seqs),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tglog_v3__log_rsp__field_indices_by_name[] = {
  0,   /* field[0] = seqs */
};
static const ProtobufCIntRange tglog_v3__log_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tglog_v3__log_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tglog_v3.LogRsp",
  "LogRsp",
  "TglogV3__LogRsp",
  "tglog_v3",
  sizeof(TglogV3__LogRsp),
  1,
  tglog_v3__log_rsp__field_descriptors,
  tglog_v3__log_rsp__field_indices_by_name,
  1,  tglog_v3__log_rsp__number_ranges,
  (ProtobufCMessageInit) tglog_v3__log_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tglog_v3__heartbeat_req__field_descriptors[1] =
{
  {
    "ping",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TglogV3__HeartbeatReq, ping),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tglog_v3__heartbeat_req__field_indices_by_name[] = {
  0,   /* field[0] = ping */
};
static const ProtobufCIntRange tglog_v3__heartbeat_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tglog_v3__heartbeat_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tglog_v3.HeartbeatReq",
  "HeartbeatReq",
  "TglogV3__HeartbeatReq",
  "tglog_v3",
  sizeof(TglogV3__HeartbeatReq),
  1,
  tglog_v3__heartbeat_req__field_descriptors,
  tglog_v3__heartbeat_req__field_indices_by_name,
  1,  tglog_v3__heartbeat_req__number_ranges,
  (ProtobufCMessageInit) tglog_v3__heartbeat_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tglog_v3__heartbeat_rsp__field_descriptors[1] =
{
  {
    "pong",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TglogV3__HeartbeatRsp, pong),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tglog_v3__heartbeat_rsp__field_indices_by_name[] = {
  0,   /* field[0] = pong */
};
static const ProtobufCIntRange tglog_v3__heartbeat_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tglog_v3__heartbeat_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tglog_v3.HeartbeatRsp",
  "HeartbeatRsp",
  "TglogV3__HeartbeatRsp",
  "tglog_v3",
  sizeof(TglogV3__HeartbeatRsp),
  1,
  tglog_v3__heartbeat_rsp__field_descriptors,
  tglog_v3__heartbeat_rsp__field_indices_by_name,
  1,  tglog_v3__heartbeat_rsp__number_ranges,
  (ProtobufCMessageInit) tglog_v3__heartbeat_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tglog_v3__req_header__field_descriptors[13] =
{
  {
    "appID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__ReqHeader, appid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "appName",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__ReqHeader, appname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "appVer",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__ReqHeader, appver),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sdkLang",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__ReqHeader, sdklang),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sdkVer",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__ReqHeader, sdkver),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sdkOS",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__ReqHeader, sdkos),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__ReqHeader, network),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protoVer",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__ReqHeader, protover),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hostIP",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__ReqHeader, hostip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ts",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TglogV3__ReqHeader, ts),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__ReqHeader, token),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tokenType",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__ReqHeader, tokentype),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sig",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__ReqHeader, sig),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tglog_v3__req_header__field_indices_by_name[] = {
  0,   /* field[0] = appID */
  1,   /* field[1] = appName */
  2,   /* field[2] = appVer */
  8,   /* field[8] = hostIP */
  6,   /* field[6] = network */
  7,   /* field[7] = protoVer */
  3,   /* field[3] = sdkLang */
  5,   /* field[5] = sdkOS */
  4,   /* field[4] = sdkVer */
  12,   /* field[12] = sig */
  10,   /* field[10] = token */
  11,   /* field[11] = tokenType */
  9,   /* field[9] = ts */
};
static const ProtobufCIntRange tglog_v3__req_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor tglog_v3__req_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tglog_v3.ReqHeader",
  "ReqHeader",
  "TglogV3__ReqHeader",
  "tglog_v3",
  sizeof(TglogV3__ReqHeader),
  13,
  tglog_v3__req_header__field_descriptors,
  tglog_v3__req_header__field_indices_by_name,
  1,  tglog_v3__req_header__number_ranges,
  (ProtobufCMessageInit) tglog_v3__req_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tglog_v3__req__field_descriptors[5] =
{
  {
    "reqID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__Req, reqid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "appMetaData",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TglogV3__Req, appmetadata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "authReq",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TglogV3__Req, req_case),
    offsetof(TglogV3__Req, authreq),
    &tglog_v3__auth_req__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "logReq",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TglogV3__Req, req_case),
    offsetof(TglogV3__Req, logreq),
    &tglog_v3__log_req__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heartbeatReq",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TglogV3__Req, req_case),
    offsetof(TglogV3__Req, heartbeatreq),
    &tglog_v3__heartbeat_req__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tglog_v3__req__field_indices_by_name[] = {
  1,   /* field[1] = appMetaData */
  2,   /* field[2] = authReq */
  4,   /* field[4] = heartbeatReq */
  3,   /* field[3] = logReq */
  0,   /* field[0] = reqID */
};
static const ProtobufCIntRange tglog_v3__req__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 11, 2 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor tglog_v3__req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tglog_v3.Req",
  "Req",
  "TglogV3__Req",
  "tglog_v3",
  sizeof(TglogV3__Req),
  5,
  tglog_v3__req__field_descriptors,
  tglog_v3__req__field_indices_by_name,
  2,  tglog_v3__req__number_ranges,
  (ProtobufCMessageInit) tglog_v3__req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tglog_v3__rsp_header__field_descriptors[4] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TglogV3__RspHeader, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__RspHeader, msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reqID",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TglogV3__RspHeader, reqid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "appMetaData",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TglogV3__RspHeader, appmetadata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tglog_v3__rsp_header__field_indices_by_name[] = {
  3,   /* field[3] = appMetaData */
  0,   /* field[0] = code */
  1,   /* field[1] = msg */
  2,   /* field[2] = reqID */
};
static const ProtobufCIntRange tglog_v3__rsp_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor tglog_v3__rsp_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tglog_v3.RspHeader",
  "RspHeader",
  "TglogV3__RspHeader",
  "tglog_v3",
  sizeof(TglogV3__RspHeader),
  4,
  tglog_v3__rsp_header__field_descriptors,
  tglog_v3__rsp_header__field_indices_by_name,
  1,  tglog_v3__rsp_header__number_ranges,
  (ProtobufCMessageInit) tglog_v3__rsp_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tglog_v3__rsp__field_descriptors[4] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TglogV3__Rsp, header),
    &tglog_v3__rsp_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "authRsp",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TglogV3__Rsp, rsp_case),
    offsetof(TglogV3__Rsp, authrsp),
    &tglog_v3__auth_rsp__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "logRsp",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TglogV3__Rsp, rsp_case),
    offsetof(TglogV3__Rsp, logrsp),
    &tglog_v3__log_rsp__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heartbeatRsp",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TglogV3__Rsp, rsp_case),
    offsetof(TglogV3__Rsp, heartbeatrsp),
    &tglog_v3__heartbeat_rsp__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tglog_v3__rsp__field_indices_by_name[] = {
  1,   /* field[1] = authRsp */
  0,   /* field[0] = header */
  3,   /* field[3] = heartbeatRsp */
  2,   /* field[2] = logRsp */
};
static const ProtobufCIntRange tglog_v3__rsp__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 11, 1 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor tglog_v3__rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tglog_v3.Rsp",
  "Rsp",
  "TglogV3__Rsp",
  "tglog_v3",
  sizeof(TglogV3__Rsp),
  4,
  tglog_v3__rsp__field_descriptors,
  tglog_v3__rsp__field_indices_by_name,
  2,  tglog_v3__rsp__number_ranges,
  (ProtobufCMessageInit) tglog_v3__rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue tglog_v3__proto_ver__enum_values_by_number[2] =
{
  { "VER_USELESS", "TGLOG_V3__PROTO_VER__VER_USELESS", 0 },
  { "MINOR", "TGLOG_V3__PROTO_VER__MINOR", 2 },
};
static const ProtobufCIntRange tglog_v3__proto_ver__value_ranges[] = {
{0, 0},{2, 1},{0, 2}
};
static const ProtobufCEnumValueIndex tglog_v3__proto_ver__enum_values_by_name[4] =
{
  { "MAJOR", 0 },
  { "MINOR", 1 },
  { "PATCH", 0 },
  { "VER_USELESS", 0 },
};
const ProtobufCEnumDescriptor tglog_v3__proto_ver__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tglog_v3.ProtoVer",
  "ProtoVer",
  "TglogV3__ProtoVer",
  "tglog_v3",
  2,
  tglog_v3__proto_ver__enum_values_by_number,
  4,
  tglog_v3__proto_ver__enum_values_by_name,
  2,
  tglog_v3__proto_ver__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tglog_v3__magic__enum_values_by_number[2] =
{
  { "MAGIC_USELESS", "TGLOG_V3__MAGIC__MAGIC_USELESS", 0 },
  { "VAL", "TGLOG_V3__MAGIC__VAL", 1537 },
};
static const ProtobufCIntRange tglog_v3__magic__value_ranges[] = {
{0, 0},{1537, 1},{0, 2}
};
static const ProtobufCEnumValueIndex tglog_v3__magic__enum_values_by_name[2] =
{
  { "MAGIC_USELESS", 0 },
  { "VAL", 1 },
};
const ProtobufCEnumDescriptor tglog_v3__magic__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tglog_v3.Magic",
  "Magic",
  "TglogV3__Magic",
  "tglog_v3",
  2,
  tglog_v3__magic__enum_values_by_number,
  2,
  tglog_v3__magic__enum_values_by_name,
  2,
  tglog_v3__magic__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tglog_v3__len__enum_values_by_number[4] =
{
  { "LEN_USELESS", "TGLOG_V3__LEN__LEN_USELESS", 0 },
  { "FLAGS", "TGLOG_V3__LEN__FLAGS", 1 },
  { "MAGIC", "TGLOG_V3__LEN__MAGIC", 2 },
  { "PACKAGE", "TGLOG_V3__LEN__PACKAGE", 4 },
};
static const ProtobufCIntRange tglog_v3__len__value_ranges[] = {
{0, 0},{4, 3},{0, 4}
};
static const ProtobufCEnumValueIndex tglog_v3__len__enum_values_by_name[6] =
{
  { "FLAGS", 1 },
  { "HEADER", 2 },
  { "LEN_USELESS", 0 },
  { "MAGIC", 2 },
  { "PACKAGE", 3 },
  { "RESERVE", 1 },
};
const ProtobufCEnumDescriptor tglog_v3__len__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tglog_v3.Len",
  "Len",
  "TglogV3__Len",
  "tglog_v3",
  4,
  tglog_v3__len__enum_values_by_number,
  6,
  tglog_v3__len__enum_values_by_name,
  2,
  tglog_v3__len__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tglog_v3__max__enum_values_by_number[5] =
{
  { "MAX_USELESS", "TGLOG_V3__MAX__MAX_USELESS", 0 },
  { "LOG_COUNT", "TGLOG_V3__MAX__LOG_COUNT", 100 },
  { "UDP_LOG_SIZE", "TGLOG_V3__MAX__UDP_LOG_SIZE", 64512 },
  { "RAW_UDP_LOG_SIZE", "TGLOG_V3__MAX__RAW_UDP_LOG_SIZE", 65507 },
  { "TCP_LOG_SIZE", "TGLOG_V3__MAX__TCP_LOG_SIZE", 524288 },
};
static const ProtobufCIntRange tglog_v3__max__value_ranges[] = {
{0, 0},{100, 1},{64512, 2},{65507, 3},{524288, 4},{0, 5}
};
static const ProtobufCEnumValueIndex tglog_v3__max__enum_values_by_name[5] =
{
  { "LOG_COUNT", 1 },
  { "MAX_USELESS", 0 },
  { "RAW_UDP_LOG_SIZE", 3 },
  { "TCP_LOG_SIZE", 4 },
  { "UDP_LOG_SIZE", 2 },
};
const ProtobufCEnumDescriptor tglog_v3__max__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tglog_v3.Max",
  "Max",
  "TglogV3__Max",
  "tglog_v3",
  5,
  tglog_v3__max__enum_values_by_number,
  5,
  tglog_v3__max__enum_values_by_name,
  5,
  tglog_v3__max__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tglog_v3__flag__enum_values_by_number[5] =
{
  { "FLAG_NONE", "TGLOG_V3__FLAG__FLAG_NONE", 0 },
  { "FLAG_COMPRESSED", "TGLOG_V3__FLAG__FLAG_COMPRESSED", 1 },
  { "FLAG_ENCRYPTED", "TGLOG_V3__FLAG__FLAG_ENCRYPTED", 2 },
  { "FLAG_COMPRESSED_HEADER", "TGLOG_V3__FLAG__FLAG_COMPRESSED_HEADER", 4 },
  { "FLAG_ENCRYPTED_HEADER", "TGLOG_V3__FLAG__FLAG_ENCRYPTED_HEADER", 8 },
};
static const ProtobufCIntRange tglog_v3__flag__value_ranges[] = {
{0, 0},{4, 3},{8, 4},{0, 5}
};
static const ProtobufCEnumValueIndex tglog_v3__flag__enum_values_by_name[5] =
{
  { "FLAG_COMPRESSED", 1 },
  { "FLAG_COMPRESSED_HEADER", 3 },
  { "FLAG_ENCRYPTED", 2 },
  { "FLAG_ENCRYPTED_HEADER", 4 },
  { "FLAG_NONE", 0 },
};
const ProtobufCEnumDescriptor tglog_v3__flag__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "tglog_v3.Flag",
  "Flag",
  "TglogV3__Flag",
  "tglog_v3",
  5,
  tglog_v3__flag__enum_values_by_number,
  5,
  tglog_v3__flag__enum_values_by_name,
  3,
  tglog_v3__flag__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
